# fly.toml app configuration file generated for background-image-gen on 2023-10-25T02:32:35+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "background-image-gen"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
